FROM node:18-alpine

ARG APP_ENV=${APP_ENV:-development}
ARG PORT=${PORT:-80}

ENV APP_ENV=${APP_ENV} \
    PORT=${PORT}

WORKDIR /usr/src/app
COPY . .

RUN yarn install
RUN yarn build

EXPOSE ${PORT}

CMD [ "yarn", "start" ]