version: '3.8'

services:

  nestjs:
    container_name: nestjs
    restart: always
    build:
        context: .
        dockerfile: Dockerfile.dev
    ports:
       - "3333:80"

  #nestjs:
  #  build: .
  #  ports:
  #    - "3333:3333"
  